name: crypting
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  bitsdojo_window: ^0.1.5
  awesome_snackbar_content: ^0.1.3
  icons_plus: ^4.0.0
  anim_search_bar: ^2.0.3
  searchbar_animation: ^0.0.4
  cryptography: ^2.7.0
  tripledes_nullsafety: ^1.0.3
  diffie_hellman: ^0.1.2
  simple_rc4: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
